
COUNTRIES=(
    (u"US",u"United States"),
    (u"CA",u"Canada"),
    (u"AF",u"Afghanistan"),
    (u"AL",u"Albania"),
    (u"DZ",u"Algeria"),
    (u"DS",u"American Samoa"),
    (u"AD",u"Andorra"),
    (u"AO",u"Angola"),
    (u"AI",u"Anguilla"),
    (u"AQ",u"Antarctica"),
    (u"AG",u"Antigua and/or Barbuda"),
    (u"AR",u"Argentina"),
    (u"AM",u"Armenia"),
    (u"AW",u"Aruba"),
    (u"AU",u"Australia"),
    (u"AT",u"Austria"),
    (u"AZ",u"Azerbaijan"),
    (u"BS",u"Bahamas"),
    (u"BH",u"Bahrain"),
    (u"BD",u"Bangladesh"),
    (u"BB",u"Barbados"),
    (u"BY",u"Belarus"),
    (u"BE",u"Belgium"),
    (u"BZ",u"Belize"),
    (u"BJ",u"Benin"),
    (u"BM",u"Bermuda"),
    (u"BT",u"Bhutan"),
    (u"BO",u"Bolivia"),
    (u"BA",u"Bosnia and Herzegovina"),
    (u"BW",u"Botswana"),
    (u"BV",u"Bouvet Island"),
    (u"BR",u"Brazil"),
    (u"IO",u"British lndian Ocean Territory"),
    (u"BN",u"Brunei Darussalam"),
    (u"BG",u"Bulgaria"),
    (u"BF",u"Burkina Faso"),
    (u"BI",u"Burundi"),
    (u"KH",u"Cambodia"),
    (u"CM",u"Cameroon"),
    (u"CV",u"Cape Verde"),
    (u"KY",u"Cayman Islands"),
    (u"CF",u"Central African Republic"),
    (u"TD",u"Chad"),
    (u"CL",u"Chile"),
    (u"CN",u"China"),
    (u"CX",u"Christmas Island"),
    (u"CC",u"Cocos (Keeling) Islands"),
    (u"CO",u"Colombia"),
    (u"KM",u"Comoros"),
    (u"CG",u"Congo"),
    (u"CK",u"Cook Islands"),
    (u"CR",u"Costa Rica"),
    (u"HR",u"Croatia (Hrvatska)"),
    (u"CU",u"Cuba"),
    (u"CY",u"Cyprus"),
    (u"CZ",u"Czech Republic"),
    (u"DK",u"Denmark"),
    (u"DJ",u"Djibouti"),
    (u"DM",u"Dominica"),
    (u"DO",u"Dominican Republic"),
    (u"TP",u"East Timor"),
    (u"EC",u"Ecudaor"),
    (u"EG",u"Egypt"),
    (u"SV",u"El Salvador"),
    (u"GQ",u"Equatorial Guinea"),
    (u"ER",u"Eritrea"),
    (u"EE",u"Estonia"),
    (u"ET",u"Ethiopia"),
    (u"FK",u"Falkland Islands (Malvinas)"),
    (u"FO",u"Faroe Islands"),
    (u"FJ",u"Fiji"),
    (u"FI",u"Finland"),
    (u"FR",u"France"),
    (u"FX",u"France, Metropolitan"),
    (u"GF",u"French Guiana"),
    (u"PF",u"French Polynesia"),
    (u"TF",u"French Southern Territories"),
    (u"GA",u"Gabon"),
    (u"GM",u"Gambia"),
    (u"GE",u"Georgia"),
    (u"DE",u"Germany"),
    (u"GH",u"Ghana"),
    (u"GI",u"Gibraltar"),
    (u"GR",u"Greece"),
    (u"GL",u"Greenland"),
    (u"GD",u"Grenada"),
    (u"GP",u"Guadeloupe"),
    (u"GU",u"Guam"),
    (u"GT",u"Guatemala"),
    (u"GN",u"Guinea"),
    (u"GW",u"Guinea-Bissau"),
    (u"GY",u"Guyana"),
    (u"HT",u"Haiti"),
    (u"HM",u"Heard and Mc Donald Islands"),
    (u"HN",u"Honduras"),
    (u"HK",u"Hong Kong"),
    (u"HU",u"Hungary"),
    (u"IS",u"Iceland"),
    (u"IN",u"India"),
    (u"ID",u"Indonesia"),
    (u"IR",u"Iran (Islamic Republic of)"),
    (u"IQ",u"Iraq"),
    (u"IE",u"Ireland"),
    (u"IT",u"Italy"),
    (u"CI",u"Ivory Coast"),
    (u"JM",u"Jamaica"),
    (u"JP",u"Japan"),
    (u"JO",u"Jordan"),
    (u"KZ",u"Kazakhstan"),
    (u"KE",u"Kenya"),
    (u"KI",u"Kiribati"),
    (u"KP",u"Korea, Democratic People's Republic of"),
    (u"KR",u"Korea, Republic of"),
    (u"KW",u"Kuwait"),
    (u"KG",u"Kyrgyzstan"),
    (u"LA",u"Lao People's Democratic Republic"),
    (u"LV",u"Latvia"),
    (u"LB",u"Lebanon"),
    (u"LS",u"Lesotho"),
    (u"LR",u"Liberia"),
    (u"LY",u"Libyan Arab Jamahiriya"),
    (u"LI",u"Liechtenstein"),
    (u"LT",u"Lithuania"),
    (u"LU",u"Luxembourg"),
    (u"MO",u"Macau"),
    (u"MK",u"Macedonia"),
    (u"MG",u"Madagascar"),
    (u"MW",u"Malawi"),
    (u"MY",u"Malaysia"),
    (u"MV",u"Maldives"),
    (u"ML",u"Mali"),
    (u"MT",u"Malta"),
    (u"MH",u"Marshall Islands"),
    (u"MQ",u"Martinique"),
    (u"MR",u"Mauritania"),
    (u"MU",u"Mauritius"),
    (u"TY",u"Mayotte"),
    (u"MX",u"Mexico"),
    (u"FM",u"Micronesia, Federated States of"),
    (u"MD",u"Moldova, Republic of"),
    (u"MC",u"Monaco"),
    (u"MN",u"Mongolia"),
    (u"MS",u"Montserrat"),
    (u"MA",u"Morocco"),
    (u"MZ",u"Mozambique"),
    (u"MM",u"Myanmar"),
    (u"NA",u"Namibia"),
    (u"NR",u"Nauru"),
    (u"NP",u"Nepal"),
    (u"NL",u"Netherlands"),
    (u"AN",u"Netherlands Antilles"),
    (u"NC",u"New Caledonia"),
    (u"NZ",u"New Zealand"),
    (u"NI",u"Nicaragua"),
    (u"NE",u"Niger"),
    (u"NG",u"Nigeria"),
    (u"NU",u"Niue"),
    (u"NF",u"Norfork Island"),
    (u"MP",u"Northern Mariana Islands"),
    (u"NO",u"Norway"),
    (u"OM",u"Oman"),
    (u"PK",u"Pakistan"),
    (u"PW",u"Palau"),
    (u"PA",u"Panama"),
    (u"PG",u"Papua New Guinea"),
    (u"PY",u"Paraguay"),
    (u"PE",u"Peru"),
    (u"PH",u"Philippines"),
    (u"PN",u"Pitcairn"),
    (u"PL",u"Poland"),
    (u"PT",u"Portugal"),
    (u"PR",u"Puerto Rico"),
    (u"QA",u"Qatar"),
    (u"RE",u"Reunion"),
    (u"RO",u"Romania"),
    (u"RU",u"Russian Federation"),
    (u"RW",u"Rwanda"),
    (u"KN",u"Saint Kitts and Nevis"),
    (u"LC",u"Saint Lucia"),
    (u"VC",u"Saint Vincent and the Grenadines"),
    (u"WS",u"Samoa"),
    (u"SM",u"San Marino"),
    (u"ST",u"Sao Tome and Principe"),
    (u"SA",u"Saudi Arabia"),
    (u"SN",u"Senegal"),
    (u"SC",u"Seychelles"),
    (u"SL",u"Sierra Leone"),
    (u"SG",u"Singapore"),
    (u"SK",u"Slovakia"),
    (u"SI",u"Slovenia"),
    (u"SB",u"Solomon Islands"),
    (u"SO",u"Somalia"),
    (u"ZA",u"South Africa"),
    (u"GS",u"South Georgia South Sandwich Islands"),
    (u"ES",u"Spain"),
    (u"LK",u"Sri Lanka"),
    (u"SH",u"St. Helena"),
    (u"PM",u"St. Pierre and Miquelon"),
    (u"SD",u"Sudan"),
    (u"SR",u"Suriname"),
    (u"SJ",u"Svalbarn and Jan Mayen Islands"),
    (u"SZ",u"Swaziland"),
    (u"SE",u"Sweden"),
    (u"CH",u"Switzerland"),
    (u"SY",u"Syrian Arab Republic"),
    (u"TW",u"Taiwan"),
    (u"TJ",u"Tajikistan"),
    (u"TZ",u"Tanzania, United Republic of"),
    (u"TH",u"Thailand"),
    (u"TG",u"Togo"),
    (u"TK",u"Tokelau"),
    (u"TO",u"Tonga"),
    (u"TT",u"Trinidad and Tobago"),
    (u"TN",u"Tunisia"),
    (u"TR",u"Turkey"),
    (u"TM",u"Turkmenistan"),
    (u"TC",u"Turks and Caicos Islands"),
    (u"TV",u"Tuvalu"),
    (u"UG",u"Uganda"),
    (u"UA",u"Ukraine"),
    (u"AE",u"United Arab Emirates"),
    (u"GB",u"United Kingdom"),
    (u"UM",u"United States minor outlying islands"),
    (u"UY",u"Uruguay"),
    (u"UZ",u"Uzbekistan"),
    (u"VU",u"Vanuatu"),
    (u"VA",u"Vatican City State"),
    (u"VE",u"Venezuela"),
    (u"VN",u"Vietnam"),
    (u"VG",u"Virigan Islands (British)"),
    (u"VI",u"Virgin Islands (U.S.)"),
    (u"WF",u"Wallis and Futuna Islands"),
    (u"EH",u"Western Sahara"),
    (u"YE",u"Yemen"),
    (u"YU",u"Yugoslavia"),
    (u"ZR",u"Zaire"),
    (u"ZM",u"Zambia"),
    (u"ZW",u"Zimbabwe")
)

CITIES = (
 (1, u'Abha'),
 (2, u'Al Artawiah'),
 (3, u'Al Baha'),
 (4, u'Al Delam'),
 (5, u"Al Der'iah"),
 (6, u'Al Hamran'),
 (7, u'Al Kharj'),
 (8, u'Al Khobar'),
 (9, u'Al Nasba'),
 (10, u'Al Ola'),
 (11, u'Al Owayqiliah'),
 (12, u'Al Qatif'),
 (13, u'Al Radifa'),
 (14, u'Al Seeh'),
 (15, u'Al Shamli'),
 (16, u"Al Ta'ef"),
 (17, u'Al Zulfi'),
 (18, u'Arar'),
 (19, u'Beesha'),
 (20, u'Buraidah'),
 (21, u'Dammam'),
 (22, u'Hail'),
 (23, u'Jazan '),
 (24, u'Jeddah'),
 (25, u'Jubail'),
 (26, u'Kamees Mushait'),
 (27, u'Khaybar'),
 (28, u'Madinah'),
 (29, u'Mekkah'),
 (30, u'Najran'),
 (31, u'Nawan'),
 (32, u'Riyadh'),
 (33, u'Sakaka'),
 (34, u'Salbokh'),
 (35, u'Tabuk'),
 (36, u'Tarif'),
 (37, u"Tayma'"),
 (38, u'Abu Dhabi'),
 (39, u'Ajman'),
 (40, u'Al Ain'),
 (41, u'Dubai'),
 (42, u'Fujairah'),
 (43, u'Ras Al Khaimah'),
 (44, u'Sharjah'),
 (45, u'Umm Al Quwain'),
 (46, u'Dibba'),
 (47, u'Musandam'),
 (48, u'Muscat'),
 (49, u'Salalah'),
 (50, u'Sohar'),
 (51, u'Sur')
)

COUNTRIES_CITIES_MAP = {u'SA': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37], u'AE': [38, 39, 40, 41, 42, 43, 44, 45], u'OM': [46, 47, 48, 49, 50, 51]}

